### PR TITLE
Storybook 6.0

### PR DESCRIPTION
**Pull request by codymorrison**
- Fix broken snapshot
- Update storybook dependencies to 6.0
- Update `i18next-xhr-backend` to `i18next-http-backend`
- Update node-sass to >= 4.14.1 due to [vulnerability](https://github.com/sass/node-sass/releases/tag/v4.14.1)

### CODE REVIEW

**Comment by omeraplak** [comment]
Hi @codymorrison ,
Thank you very much for your contribution. Can you fix test?

**Comment by razorsky** [comment]
Hello, when are you going to merge please ?

**Comment by omeraplak** [comment]
@razorsky Hi,
Could you update LocaleButton snapshot?

Build logs;
https://travis-ci.org/github/pankod/next-boilerplate/builds/720490533

**Review by omeraplak — APPROVED** [review]

**Comment by omeraplak** [comment]
@codymorrison Hi,
Could you fix conflicts?

**Pull request closed without merging**
